// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2.Models;

namespace Project2.Migrations
{
    [DbContext(typeof(ToursContext))]
    [Migration("20220323154137_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Project2.Models.TimeSlots", b =>
                {
                    b.Property<int>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TimeId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            TimeId = 1,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeId = 2,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeId = 3,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeId = 4,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeId = 5,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeId = 6,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeId = 7,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeId = 8,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeId = 9,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeId = 10,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeId = 11,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeId = 12,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeId = 13,
                            Day = "Monday",
                            IsAvailable = true,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeId = 14,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeId = 15,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeId = 16,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeId = 17,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeId = 18,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeId = 19,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeId = 20,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeId = 21,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeId = 22,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeId = 23,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeId = 24,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeId = 25,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeId = 26,
                            Day = "Tuesday",
                            IsAvailable = true,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeId = 27,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeId = 28,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeId = 29,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeId = 30,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeId = 31,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeId = 32,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeId = 33,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeId = 34,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeId = 35,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeId = 36,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeId = 37,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeId = 38,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeId = 39,
                            Day = "Wednesday",
                            IsAvailable = true,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeId = 40,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeId = 41,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeId = 42,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeId = 43,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeId = 44,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeId = 45,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeId = 46,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeId = 47,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeId = 48,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeId = 49,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeId = 50,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeId = 51,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeId = 52,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeId = 53,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeId = 54,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "9:00 PM"
                        },
                        new
                        {
                            TimeId = 55,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "10:00 PM"
                        },
                        new
                        {
                            TimeId = 56,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "11:00 PM"
                        },
                        new
                        {
                            TimeId = 57,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeId = 58,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeId = 59,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeId = 60,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeId = 61,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeId = 62,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeId = 63,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeId = 64,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeId = 65,
                            Day = "Thursday",
                            IsAvailable = true,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeId = 66,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeId = 67,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeId = 68,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeId = 69,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeId = 70,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeId = 71,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeId = 72,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeId = 73,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeId = 74,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeId = 75,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeId = 76,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeId = 77,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeId = 78,
                            Day = "Friday",
                            IsAvailable = true,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeId = 79,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeId = 80,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeId = 81,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeId = 82,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeId = 83,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeId = 84,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeId = 85,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeId = 86,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeId = 87,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeId = 88,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeId = 89,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeId = 90,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeId = 91,
                            Day = "Saturday",
                            IsAvailable = true,
                            Time = "8:00 PM"
                        },
                        new
                        {
                            TimeId = 92,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "8:00 AM"
                        },
                        new
                        {
                            TimeId = 93,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "9:00 AM"
                        },
                        new
                        {
                            TimeId = 94,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "10:00 AM"
                        },
                        new
                        {
                            TimeId = 95,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "11:00 AM"
                        },
                        new
                        {
                            TimeId = 96,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "12:00 PM"
                        },
                        new
                        {
                            TimeId = 97,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "1:00 PM"
                        },
                        new
                        {
                            TimeId = 98,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "2:00 PM"
                        },
                        new
                        {
                            TimeId = 99,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "3:00 PM"
                        },
                        new
                        {
                            TimeId = 100,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "4:00 PM"
                        },
                        new
                        {
                            TimeId = 101,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "5:00 PM"
                        },
                        new
                        {
                            TimeId = 102,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "6:00 PM"
                        },
                        new
                        {
                            TimeId = 103,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "7:00 PM"
                        },
                        new
                        {
                            TimeId = 104,
                            Day = "Sunday",
                            IsAvailable = true,
                            Time = "8:00 PM"
                        });
                });

            modelBuilder.Entity("Project2.Models.Tours", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeSlotTimeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TourId");

                    b.HasIndex("TimeSlotTimeId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Project2.Models.Tours", b =>
                {
                    b.HasOne("Project2.Models.TimeSlots", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
